export const ACTIONS = {
  SET_OPTIONS_PIZZA:"SET_OPTIONS_PIZZA",
  SET_IS_DISABLE:"SET_IS_DISABLE",
  SET_ITEM_OF_ORDER:"SET_ITEM_OF_ORDER",
  SET_ITEM_ON_LS:"SET_ITEM_ON_LS",
  SET_UI_PRICE:"SET_UI_PRICE"
};